### ISSUE TITLE
Typo when connecting to AWS

### ISSUE THREAD

**Issue by davidgasquez** [jwinternheimer/buffer#1]
Heya @jwinternheimer! I've noticed the forecaster is failing and after checking the logs I've noticed is not reading the environment variables properly.

The error might be caused by this line: https://github.com/jwinternheimer/buffer/blob/master/R/write_to_redshift.R#L39 

These are the logs:

```
Enter your AWS access key: 
Enter your AWS secret access key: 
Error in Sys.setenv(AWS_SECRET_ACCESS_KEY = secret_keu) : 
  object 'secret_keu' not found
Calls: main -> <Anonymous> -> Sys.setenv
Execution halted
```

Let me know if I can share anything else!

**Comment by jwinternheimer** [comment]
Oh wow, thanks for filing this @davidgasquez! Pushing a fix now!

**Comment by jwinternheimer** [comment]
Issue has been fixed here: https://github.com/jwinternheimer/buffer/commit/bb447a821db88994cd047988edd66b703b6e4f20

Thanks again for bringing this up!
