### ISSUE TITLE
Environment secrets dependencies

### ISSUE THREAD

**Issue by davidgasquez** [jwinternheimer/buffer#2]
Heya @jwinternheimer! While setting up a service that uses this package I spotted that for the package to work, it requires a few environmental variables.

For example, the [`mrr-forecaster`](https://github.com/bufferapp/mrr-forecaster) is using the Redshift variables but doesn't require the Looker or AWS ones. When running the script without the Looker or AWS environment keys it's failing.

Is there a way to make this dependencies optional? Would love to hear how difficult that would be since having these variables as optional would simplify the setup in production.

**Comment by jwinternheimer** [comment]
Hey @davidgasquez, thanks for creating this issue! 

I think we may be able to remove those, however we need the Looker credentials to pull data from Looker ([here](https://github.com/bufferapp/mrr-forecaster/blob/58538af48786af29d427ef4cc1068e2da3d3dda5/forecast.R#L21)) and we need the AWS credentials in the `write_to_redshift()` function. Does that make sense?

**Comment by davidgasquez** [comment]
Ups, that's totally right, my bad. :see_no_evil: Sorry for the false alarm!
