### ISSUE TITLE
Move this project over to the bufferapp organization

### ISSUE THREAD

**Issue by michael-erasmus** [jwinternheimer/buffer#3]
Hey @jwinternheimer! I noticed your discussion with @mallen5311 about the BuffeR package we still had in the bufferapp organization. Since we weren't using that one and your repo is the active one, I went ahead and deleted the old bufferapp/buffeR repo. 

I was curious how you felt about perhaps transferring ownership of this repo to the bufferapp org, just to make reduce the chance of confusion?

**Comment by jwinternheimer** [comment]
This has been done :)
